### ISSUE TITLE
Fails in CircleCI pipeline

### ISSUE THREAD

**Issue by curtisburns** [akillmer/shopify-theme-sync-plugin#1]
When running webpack in CircleCI, it seems to fail with:

```> webpack --mode=production
 

 
/home/circleci/project/index2.js:51
 
  deployFile = (file) => {
 
             ^
 

 
SyntaxError: Unexpected token =
 
    at new Script (vm.js:83:7)
 
    at NativeCompileCache._moduleCompile (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
 
    at Module._compile (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
 
    at Module.load (internal/modules/cjs/loader.js:653:32)
 
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
 
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
 
    at Module.require (internal/modules/cjs/loader.js:692:17)
 
    at require (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
 
    at Object.<anonymous> (/home/circleci/project/webpack.config.js:3:32)
 
    at Module._compile (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
 
    at Module.load (internal/modules/cjs/loader.js:653:32)
 
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
 
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
 
    at Module.require (internal/modules/cjs/loader.js:692:17)
 
    at require (/home/circleci/project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
 
    at WEBPACK_OPTIONS (/home/circleci/project/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
 
    at requireConfig (/home/circleci/project/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
 
    at /home/circleci/project/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
 
    at Array.forEach (<anonymous>)
 
    at module.exports (/home/circleci/project/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
 
    at yargs.parse (/home/circleci/project/node_modules/webpack-cli/bin/cli.js:71:45)
 
    at Object.parse (/home/circleci/project/node_modules/yargs/yargs.js:567:18)
 
    at /home/circleci/project/node_modules/webpack-cli/bin/cli.js:49:8
 
    at Object.<anonymous> (/home/circleci/project/node_modules/webpack-cli/bin/cli.js:366:3)
 
    at Module._compile (internal/modules/cjs/loader.js:778:30)
 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
 
    at Module.load (internal/modules/cjs/loader.js:653:32)
 
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
 
npm ERR! code ELIFECYCLE
 
npm ERR! errno 1

 
npm ERR! Exit status 1
 
npm ERR! 

 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 ```
I imagine this is something to do with it being es6 as I made a copy, converted to es5 and imported instead and everything worked fine. Probably more of a CircleCI issue but fails despite running on node v10. Works great on my local though!

**Comment by akillmer** [comment]
I'd be happy to accept a PR for an ES5 version of this. Thanks for the feedback!
